import type { CalculatorConfig } from '@/lib/types';

export const roas: CalculatorConfig = {
  slug: 'roas-calculator',
  name: 'ROAS Calculator',
  h1: 'ROAS Calculator (Return on Ad Spend)',
  title: 'ROAS Calculator — Return on Ad Spend',
  description:
    'Free ROAS calculator. Enter revenue and ad spend to get return on ad spend, your break-even ROAS, profit after ads and ACOS. Instant, no signup.',
  blurb:
    'See your return on ad spend — and the break-even ROAS your margin actually requires.',
  category: 'Advertising & Marketing',
  keywords: [
    'roas calculator',
    'return on ad spend calculator',
    'break even roas calculator',
    'how to calculate roas',
    'acos calculator',
  ],

  formulaId: 'roas',
  formulaDisplay: 'ROAS = Revenue from ads ÷ Total ad cost    ·    Break-even ROAS = 1 ÷ Gross margin',

  fields: [
    {
      id: 'revenue',
      label: 'Revenue attributed to ads',
      type: 'currency',
      defaultValue: 120000,
      min: 0,
      step: 1000,
      help: 'Sales generated by the campaigns you are measuring, in the same period.',
    },
    {
      id: 'adSpend',
      label: 'Ad spend',
      type: 'currency',
      defaultValue: 30000,
      min: 0,
      step: 500,
      help: 'Media cost paid to the platform.',
    },
    {
      id: 'grossMarginPct',
      label: 'Gross margin',
      type: 'percent',
      defaultValue: 45,
      min: 0,
      max: 100,
      step: 1,
      help: 'Revenue minus COGS, shipping and fees. This is what sets break-even ROAS.',
    },
    {
      id: 'otherAdCosts',
      label: 'Other advertising costs',
      type: 'currency',
      defaultValue: 3000,
      min: 0,
      step: 100,
      optional: true,
      help: 'Agency fees, creative production, ad tools. Excluded from platform-reported ROAS.',
    },
  ],

  results: [
    {
      id: 'roas',
      label: 'ROAS',
      format: 'ratio',
      primary: true,
      help: 'Revenue returned per $1 of ad cost. Compare it against break-even below.',
    },
    {
      id: 'breakEvenRoas',
      label: 'Break-even ROAS',
      format: 'ratio',
      help: 'The ROAS at which you make exactly nothing. Anything below this loses money.',
    },
    { id: 'profitAfterAds', label: 'Gross profit after ad costs', format: 'currency' },
    { id: 'acosPct', label: 'ACOS (ad cost of sale)', format: 'percent' },
  ],

  intro: [
    'Return on ad spend divides the revenue a campaign produced by what it cost to run. It is the fastest read on whether advertising is working — but only once you compare it against the break-even ROAS your gross margin demands, which is the step most reports leave out.',
    'Enter your figures below. Everything runs in your browser — nothing is uploaded, stored or sent anywhere.',
  ],

  sections: [
    {
      heading: 'How to calculate ROAS',
      body: [
        'Divide revenue attributed to your ads by the cost of those ads. $120,000 of revenue from $30,000 of spend is a 4:1 ROAS, usually written as 4.0 or 400%. Add agency fees and creative production and the same campaign is 3.6:1 — which is the number that reflects what you actually paid.',
        'ROAS differs from ROI in what it counts. ROI measures profit against total investment; ROAS measures revenue against media cost alone. That makes ROAS easy to compute and easy to misread, because a campaign can post an impressive ROAS while losing money on every order.',
      ],
      bullets: [
        'Include agency fees, creative costs and ad tooling. Platform-reported ROAS never does.',
        'Keep revenue and spend in the same window, and mind the attribution lag on considered purchases.',
        'Report new-customer ROAS separately — blended ROAS credits ads with repeat purchases they did not cause.',
      ],
    },
    {
      heading: 'Break-even ROAS is the number that matters',
      body: [
        'A 4:1 ROAS means nothing on its own. What matters is where it sits relative to break-even, and break-even is set entirely by your gross margin: divide 1 by your margin. At a 45% margin you need 2.22:1 just to avoid losing money. At 25% you need 4:1 — so a "great" 3.5:1 campaign is quietly unprofitable.',
        'This is why the same ROAS target cannot be copied between businesses. A software company at 90% margin breaks even at 1.11:1 and can bid aggressively; a retailer at 20% needs 5:1 before a single dollar of profit appears. Work out your break-even first, then set targets as a multiple of it rather than picking a round number.',
      ],
    },
    {
      heading: 'Attribution: why platform ROAS is always higher',
      body: [
        'Every ad platform reports a ROAS flattering to itself. Default attribution windows are generous, view-through conversions credit impressions nobody clicked, and each platform claims the same sale independently — add up the reported revenue across Meta, Google and TikTok and it commonly exceeds what the business actually took.',
        'The correction is to reconcile against your own numbers. Compare total platform-reported revenue with actual revenue in your accounting system and apply the resulting haircut consistently. Better still, run incrementality tests: turn a channel off in a region and measure what actually happens to sales. The gap between reported and incremental ROAS is often larger than the difference between a good campaign and a bad one.',
      ],
    },
    {
      heading: 'ROAS, ACOS and MER',
      body: [
        'ACOS is simply the inverse of ROAS expressed as a percentage — ad cost divided by revenue. A 4:1 ROAS is a 25% ACOS. Amazon sellers tend to use ACOS, everyone else uses ROAS, and they carry identical information.',
        'MER, or marketing efficiency ratio, divides total revenue by total marketing spend across all channels. Because it uses your real top-line revenue rather than platform-claimed attribution, it cannot be inflated by double counting, which makes it the more honest number for judging whether marketing as a whole is working. Use channel ROAS to allocate budget between platforms, and MER to decide whether the total budget is right.',
      ],
    },
  ],

  workedExample: {
    scenario:
      'A DTC brand spends $30,000 on Meta ads in a month plus $3,000 in agency and creative fees, and attributes $120,000 of revenue to those campaigns. Gross margin after COGS, shipping and payment fees is 45%.',
    inputs: [
      { label: 'Revenue attributed to ads', value: '$120,000' },
      { label: 'Ad spend', value: '$30,000' },
      { label: 'Gross margin', value: '45%' },
      { label: 'Other advertising costs', value: '$3,000' },
    ],
    steps: [
      'Total ad cost = $30,000 + $3,000 = $33,000',
      'ROAS = $120,000 ÷ $33,000 = about 3.64:1',
      'Break-even ROAS = 1 ÷ 0.45 = about 2.22:1',
      'Gross profit after ad costs = ($120,000 × 45%) − $33,000 = $21,000',
      'ACOS = $33,000 ÷ $120,000 = 27.5%',
    ],
    takeaway:
      'At 3.64:1 against a 2.22:1 break-even the campaign is genuinely profitable, clearing $21,000 of gross profit. Note that the platform would have reported 4.0:1 by ignoring the agency and creative fees — a 10% overstatement that would matter a great deal if margin were thinner.',
  },

  faqs: [
    {
      q: 'What is a good ROAS?',
      a: 'It depends entirely on your gross margin. Break-even ROAS is 1 ÷ margin, so a 45%-margin business needs 2.22:1 to break even while a 20%-margin business needs 5:1. Aim for a multiple of your break-even, not a fixed number.',
    },
    {
      q: 'What is the difference between ROAS and ROI?',
      a: 'ROAS compares revenue to ad spend only. ROI compares profit to total investment including product costs, overhead and labour. A campaign can show a strong ROAS and still deliver a negative ROI.',
    },
    {
      q: 'How do I calculate break-even ROAS?',
      a: 'Divide 1 by your gross margin. A 40% margin gives 1 ÷ 0.40 = 2.5:1. Below that, each additional sale from ads loses money.',
    },
    {
      q: 'Why is my platform ROAS higher than my actual results?',
      a: 'Platforms use generous attribution windows, count view-through conversions, and each claims the same sale. They also exclude agency fees and creative costs. Reconcile platform-reported revenue against your accounting system and apply the haircut consistently.',
    },
    {
      q: 'Should I use blended or new-customer ROAS?',
      a: 'Both. Blended ROAS shows overall efficiency but credits advertising with repeat purchases it did not cause. New-customer ROAS is the honest measure of whether acquisition spend is working.',
    },
    {
      q: 'Does this calculator send my data anywhere?',
      a: 'No. Every calculation runs locally in your browser using JavaScript. Nothing is transmitted to a server, logged or stored.',
    },
  ],

  related: ['cac-calculator', 'ltv-calculator', 'pricing-margin-calculator', 'ltv-cac-ratio-calculator'],

  variants: [
    {
      slug: 'for-facebook-ads',
      label: 'Facebook & Instagram ads',
      audience: 'advertisers running Meta campaigns',
      intro:
        'Meta reports the most generous ROAS of any major platform, and the gap between its number and your bank account is usually the largest single source of confusion in DTC marketing. Post-ATT signal loss made modelled conversions a bigger share of reported results, so Meta ROAS should be treated as a directional optimisation signal rather than a financial fact.',
      costsToInclude: [
        'Meta media spend across all campaigns and placements',
        'Creative production — UGC fees, editing, static and video assets',
        'Agency or media buyer fees, typically 10–20% of spend',
        'Conversions API / server-side tracking infrastructure',
      ],
      benchmark: {
        typical:
          'Reported ROAS of 2:1 to 5:1 is common in DTC; actual incremental ROAS is frequently 30–50% lower.',
        good: 'Reported ROAS at least 1.5× your break-even, to absorb attribution inflation.',
        note: 'Compare Meta-reported revenue against total store revenue each month. If reported attribution exceeds about 70% of your actual sales, the platform is claiming credit for demand it did not create.',
      },
      defaults: { revenue: 120000, adSpend: 30000, grossMarginPct: 45, otherAdCosts: 4500 },
      example: {
        scenario:
          'A DTC brand spends $30,000 on Meta with a $4,500 agency fee, and Meta reports $120,000 of attributed revenue at a 45% gross margin.',
        inputs: [
          { label: 'Revenue attributed to ads', value: '$120,000' },
          { label: 'Ad spend', value: '$30,000' },
          { label: 'Gross margin', value: '45%' },
          { label: 'Other advertising costs', value: '$4,500' },
        ],
        steps: [
          'Total ad cost = $30,000 + $4,500 = $34,500',
          'True ROAS = $120,000 ÷ $34,500 = about 3.48:1 (Meta would report 4.0:1)',
          'Break-even ROAS = 1 ÷ 0.45 = 2.22:1',
          'Profit after ads = ($120,000 × 45%) − $34,500 = $19,500',
        ],
        takeaway:
          'Profitable with room to spare — but if attribution is overstating revenue by 30%, real ROAS is nearer 2.4:1 and the margin of safety mostly disappears. Run a geo holdout before scaling on the reported figure.',
      },
      faqs: [
        {
          q: 'Should I use 7-day click or 1-day click attribution for ROAS?',
          a: 'One-day click is closer to incremental truth; seven-day click plus one-day view is closer to what Meta optimises against. Pick one, use it consistently, and reconcile whichever you choose against actual revenue.',
        },
      ],
    },

    {
      slug: 'for-google-ads',
      label: 'Google Ads',
      audience: 'advertisers running Google Search, Shopping and Performance Max',
      intro:
        'Google ROAS is dominated by one distinction that most account-level reporting hides: brand versus non-brand. Branded search converts at several times the rate of everything else and would largely have converted anyway, so a blended account ROAS routinely disguises unprofitable prospecting behind traffic you already owned.',
      costsToInclude: [
        'Search, Shopping, Performance Max and YouTube spend',
        'Branded search spend, reported separately from prospecting',
        'Agency management fees and bid-management tooling',
        'Feed management and creative for Shopping and PMax',
      ],
      benchmark: {
        typical:
          'Branded search commonly returns 8:1 or higher; non-brand search and Shopping typically 2:1 to 4:1.',
        good: 'Non-brand ROAS above break-even on its own, without branded traffic subsidising it.',
        note: 'Segment brand from non-brand before judging anything. An account showing 5:1 blended can easily be 12:1 on brand and 1.8:1 on prospecting — which means the growth engine is losing money.',
      },
      defaults: { revenue: 96000, adSpend: 24000, grossMarginPct: 45, otherAdCosts: 3000 },
      example: {
        scenario:
          'A retailer spends $24,000 on Google Ads plus $3,000 in management fees, generating $96,000 in attributed revenue at 45% margin.',
        inputs: [
          { label: 'Revenue attributed to ads', value: '$96,000' },
          { label: 'Ad spend', value: '$24,000' },
          { label: 'Gross margin', value: '45%' },
          { label: 'Other advertising costs', value: '$3,000' },
        ],
        steps: [
          'Total ad cost = $24,000 + $3,000 = $27,000',
          'ROAS = $96,000 ÷ $27,000 = about 3.56:1',
          'Break-even ROAS = 2.22:1',
          'Profit after ads = ($96,000 × 45%) − $27,000 = $16,200',
        ],
        takeaway:
          'Healthy at account level. Before increasing budget, split out branded search — if it accounts for a third of the revenue at 10:1, the remaining non-brand ROAS is close to 2.4:1 and far less comfortable.',
      },
      faqs: [
        {
          q: 'Should branded search be included in ROAS?',
          a: 'Report it separately. Most branded clicks would have reached you organically, so including them inflates account ROAS and hides whether prospecting is profitable.',
        },
      ],
    },

    {
      slug: 'for-amazon-ads',
      label: 'Amazon Ads',
      audience: 'Amazon sellers and brands',
      intro:
        'Amazon sellers usually work in ACOS rather than ROAS, and they have to contend with a fee structure that eats margin before advertising is even considered: referral fees, FBA fulfilment and storage together commonly take 30–40% of the sale price. That pushes break-even ACOS far lower than sellers expect.',
      costsToInclude: [
        'Sponsored Products, Brands and Display spend',
        'Amazon referral fees, typically 8–15%',
        'FBA fulfilment and storage fees',
        'Product cost and inbound shipping',
        'Coupons and Lightning Deal fees used alongside ads',
      ],
      benchmark: {
        typical:
          'ACOS of 15–30% is common for established products; launch campaigns often run 50%+ deliberately.',
        good: 'ACOS comfortably below break-even, with TACOS trending down as organic rank improves.',
        note: 'Watch TACOS — total ad spend divided by total sales including organic. Falling TACOS at stable revenue means advertising is building organic rank rather than renting it.',
      },
      defaults: { revenue: 80000, adSpend: 16000, grossMarginPct: 30, otherAdCosts: 1000 },
      example: {
        scenario:
          'A seller spends $16,000 on Sponsored Products plus $1,000 on management, generating $80,000 in ad-attributed sales at a 30% margin after referral and FBA fees.',
        inputs: [
          { label: 'Revenue attributed to ads', value: '$80,000' },
          { label: 'Ad spend', value: '$16,000' },
          { label: 'Gross margin', value: '30%' },
          { label: 'Other advertising costs', value: '$1,000' },
        ],
        steps: [
          'Total ad cost = $16,000 + $1,000 = $17,000',
          'ROAS = $80,000 ÷ $17,000 = about 4.7:1, i.e. ACOS of about 21%',
          'Break-even ROAS = 1 ÷ 0.30 = 3.33:1, i.e. break-even ACOS of 30%',
          'Profit after ads = ($80,000 × 30%) − $17,000 = $7,000',
        ],
        takeaway:
          'A 21% ACOS against a 30% break-even leaves real profit. The thin 30% margin is what makes Amazon unforgiving: a nine-point rise in ACOS wipes out the entire gain.',
      },
    },

    {
      slug: 'for-tiktok-ads',
      label: 'TikTok Ads',
      audience: 'brands advertising on TikTok',
      intro:
        'TikTok ROAS is heavily influenced by creative fatigue — assets burn out in days rather than weeks, so production volume is a genuine cost line rather than an afterthought. View-through attribution is also a larger share of reported conversions than on other platforms, which makes reported ROAS look better and incremental ROAS harder to pin down.',
      costsToInclude: [
        'TikTok media spend',
        'High-volume creative production — the largest hidden cost on this channel',
        'Creator and Spark Ads licensing fees',
        'Agency or in-house buyer time',
      ],
      benchmark: {
        typical: 'Reported ROAS of 1.5:1 to 3:1 is common; lower than Meta but often at lower CPMs.',
        good: 'ROAS above break-even after fully loading creative production costs.',
        note: 'Budget creative as a percentage of media spend — 15–25% is realistic. Teams that omit it consistently overestimate TikTok profitability.',
      },
      defaults: { revenue: 60000, adSpend: 25000, grossMarginPct: 45, otherAdCosts: 5000 },
      example: {
        scenario:
          'A brand spends $25,000 on TikTok plus $5,000 on creator content and editing, generating $60,000 in attributed revenue at a 45% margin.',
        inputs: [
          { label: 'Revenue attributed to ads', value: '$60,000' },
          { label: 'Ad spend', value: '$25,000' },
          { label: 'Gross margin', value: '45%' },
          { label: 'Other advertising costs', value: '$5,000' },
        ],
        steps: [
          'Total ad cost = $25,000 + $5,000 = $30,000',
          'ROAS = $60,000 ÷ $30,000 = 2.0:1',
          'Break-even ROAS = 2.22:1',
          'Profit after ads = ($60,000 × 45%) − $30,000 = −$3,000',
        ],
        takeaway:
          'A 2.0:1 ROAS reads acceptable and is actually a $3,000 loss, because break-even is 2.22:1. This is the exact failure mode break-even ROAS exists to catch — and it is entirely driven by the creative costs the platform never sees.',
      },
    },

    {
      slug: 'for-lead-generation',
      label: 'lead generation',
      audience: 'lead-gen businesses and service companies',
      intro:
        'Lead generation has no immediate revenue to divide by, so conventional ROAS does not apply until you convert leads into expected value. The workable approach is to compute revenue per lead — close rate multiplied by average deal value — and use that as the revenue input, which turns ROAS into a forward-looking estimate rather than a measurement.',
      costsToInclude: [
        'Media spend across search and social',
        'Landing page and creative production',
        'Lead verification, enrichment and routing tools',
        'Sales follow-up time, which is a real cost of a lead',
      ],
      benchmark: {
        typical:
          'Cost per lead varies enormously by sector; what matters is cost per qualified lead against deal value.',
        good: 'Expected revenue per lead at 3× or more of cost per lead.',
        note: 'Use qualified leads, not raw form fills. Unqualified lead volume is the easiest number in marketing to inflate and the least connected to revenue.',
      },
      defaults: { revenue: 90000, adSpend: 20000, grossMarginPct: 60, otherAdCosts: 4000 },
      example: {
        scenario:
          'A home services company spends $20,000 on ads plus $4,000 on landing pages and lead tooling, generating 300 qualified leads. It closes 20% at an average job value of $1,500, so expected revenue is 300 × 0.20 × $1,500 = $90,000. Gross margin is 60%.',
        inputs: [
          { label: 'Revenue attributed to ads (expected)', value: '$90,000' },
          { label: 'Ad spend', value: '$20,000' },
          { label: 'Gross margin', value: '60%' },
          { label: 'Other advertising costs', value: '$4,000' },
        ],
        steps: [
          'Expected revenue = 300 leads × 20% close rate × $1,500 = $90,000',
          'Total ad cost = $20,000 + $4,000 = $24,000',
          'ROAS = $90,000 ÷ $24,000 = 3.75:1',
          'Break-even ROAS = 1 ÷ 0.60 = about 1.67:1',
        ],
        takeaway:
          'Comfortably profitable, and note where the leverage sits: raising the close rate from 20% to 25% lifts ROAS to 4.7:1 without spending another dollar on media.',
      },
      faqs: [
        {
          q: 'How do I calculate ROAS for lead generation?',
          a: 'Convert leads to expected revenue first: qualified leads × close rate × average deal value. Divide that by total ad cost. It is an estimate, so revisit it as actual close rates come in.',
        },
      ],
    },

    {
      slug: 'for-b2b-saas',
      label: 'B2B SaaS',
      audience: 'B2B SaaS marketing teams',
      intro:
        'ROAS fits B2B SaaS badly. Sales cycles run months, the first month of revenue is a fraction of contract value, and a customer acquired today keeps paying for years. Measured on first-month revenue almost every B2B SaaS campaign looks catastrophic — the fix is to compute ROAS against first-year contract value or LTV, and to state which you used.',
      costsToInclude: [
        'Paid search, paid social and review-site spend',
        'Content and webinar production',
        'Marketing salaries attributable to demand generation',
        'Attribution and marketing automation tooling',
      ],
      benchmark: {
        typical: 'ROAS of 3:1 to 5:1 against first-year contract value is a reasonable target.',
        good: 'Positive ROAS on first-year ACV, with CAC payback under 12 months.',
        note: 'Offset your periods for the sales cycle. Comparing this month\'s spend with this month\'s closed revenue understates ROAS badly whenever budgets are growing.',
      },
      defaults: { revenue: 234000, adSpend: 40000, grossMarginPct: 80, otherAdCosts: 20000 },
      example: {
        scenario:
          'A SaaS company spends $40,000 on paid media plus $20,000 in demand-gen salaries per quarter, producing 30 new customers at $650 MRR — $234,000 of first-year contract value. Gross margin is 80%.',
        inputs: [
          { label: 'Revenue attributed to ads (first-year ACV)', value: '$234,000' },
          { label: 'Ad spend', value: '$40,000' },
          { label: 'Gross margin', value: '80%' },
          { label: 'Other advertising costs', value: '$20,000' },
        ],
        steps: [
          'First-year value = 30 customers × $650 × 12 = $234,000',
          'Total cost = $40,000 + $20,000 = $60,000',
          'ROAS on first-year ACV = $234,000 ÷ $60,000 = 3.9:1',
          'Break-even ROAS = 1 ÷ 0.80 = 1.25:1',
        ],
        takeaway:
          'Strong on a first-year basis. The same campaign measured on first-month revenue would show 0.33:1 and look like a disaster — which is why the measurement window has to match the business model.',
      },
    },
  ],
};
